# Generated by Django 4.2.5 on 2023-12-19 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Difficulty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Difficulty',
                'verbose_name_plural': 's',
            },
        ),
        migrations.CreateModel(
            name='ExerciseType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'ExerciseType',
                'verbose_name_plural': 's',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('photo', models.ImageField(upload_to='')),
                ('notes', models.FileField(upload_to='')),
                ('video', models.URLField()),
                ('ex_difficulty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrumForBeginersApp.difficulty')),
                ('ex_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DrumForBeginersApp.exercisetype')),
            ],
            options={
                'verbose_name': 'Exercise',
                'verbose_name_plural': 's',
            },
        ),
    ]
